# quick_replication_limit: the amount of replicated activities to check 1 second after adding/updating/removing the original 
confirm: False
test_server: "int.orcid.org"
replication_server: "int.orcid.org"
protocol: "HTTP/2"
number_of_activities: 10
number_of_activities_sample: 5
quick_replication_limit: 5
orcid_id: "0000-0003-1300-2139"
access_token: ""
source: "Replication test"