# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      server:
        description: 'Server'
        required: true
        default: 'qa.orcid.org'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      selenium:
        image: selenium/standalone-chrome
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 2.7
      uses: actions/setup-python@v1
      with:
        python-version: 2.7
    - name: Install dependencies
      env: 
        FIXER_IO_ACCESS_TOKEN: ${{ secrets.FIXER_IO_ACCESS_TOKEN }}
      run: |
        python -m pip install --upgrade pip
        pip install -q -r orcid/requirements.txt
        echo "test_server='${{github.event.inputs.server}}'" >> 'orcid/properties.py'
        echo "memberClientId='${{secrets.QA_MEMBER_CLIENT_ID}}'" >> 'orcid/properties.py'       
        echo "memberClientSecret='${{secrets.QA_MEMBER_CLIENT_SECRET}}'" >> 'orcid/properties.py' 
        echo "notifyToken='${{secrets.QA_NOTIFY_TOKEN}}'" >> 'orcid/properties.py' 
        echo "staticOBOUserAccess='${{secrets.QA_STATIC_OBO_USER_TOKEN}}'" >> 'orcid/properties.py' 
        echo "staticId='${{secrets.QA_STATIC_ORCID}}'" >> 'orcid/properties.py' 
        echo "staticAccess='${{secrets.QA_STATIC_TOKEN}}'" >> 'orcid/properties.py' 
        echo "publicClientId='${{secrets.QA_STATIC_ORCID}}'" >> 'orcid/properties.py' 
        echo "publicClientSecret='${{secrets.QA_STATIC_TOKEN}}'" >> 'orcid/properties.py' 
        echo "premiumClientId='${{secrets.QA_STATIC_ORCID}}'" >> 'orcid/properties.py' 
        echo "premiumClientSecret='${{secrets.QA_STATIC_TOKEN}}'" >> 'orcid/properties.py' 
    - name: Prepare Selenium
      # https://github.com/marketplace/actions/setup-chromedriver
      uses: nanasess/setup-chromedriver@master
    - name: geckodriver/firefox
      run: |
        echo "geckodriver/firefox"
        which geckodriver
        geckodriver --version
        which firefox
        firefox --version
    - name: Test public record
      run: py.test --junitxml orcid/.py_env/Scripts/results/test_public_record.xml orcid/test_public_record.py
    - name: Test limited record
      run: py.test --junitxml orcid/.py_env/Scripts/results/test_limited_record.xml orcid/test_limited_record.py
    - name: Test 2.0 API all endpoints
      run: py.test --junitxml orcid/.py_env/Scripts/results/test_20api_all_endpoints.xml orcid/test_20api_all_endpoints.py
    - name: Test 2.1 API all endpoints
      run: py.test --junitxml orcid/.py_env/Scripts/results/test_21api_all_endpoints.xml orcid/test_21api_all_endpoints.py
    - name: Test 3.0 API all endpoints
      run: py.test --junitxml orcid/.py_env/Scripts/results/test_30api_all_endpoints.xml orcid/test_30api_all_endpoints.py
    - name: Test 3.0 API OBO user all endpoints
      run: py.test --junitxml orcid/.py_env/Scripts/results/test_30api_obo_user_all_endpoints.xml orcid/test_30api_obo_user_all_endpoints.py
    - name: Test 3.0 RC1 API all endpoints
      run: py.test --junitxml orcid/.py_env/Scripts/results/test_30rc1api_all_endpoints.xml orcid/test_30rc1api_all_endpoints.py
    - name: Test 3.0 RC2 API all endpoints
      run: py.test --junitxml orcid/.py_env/Scripts/results/test_30rc2api_all_endpoints.xml orcid/test_30rc2api_all_endpoints.py
    - name: Test scope methods
      run: py.test --junitxml orcid/.py_env/Scripts/results/test_scope_methods.xml orcid/test_scope_methods.py
    - name: Test read endpoints
      run: py.test --junitxml orcid/.py_env/Scripts/results/test_read_endpoints.xml orcid/test_read_endpoints.py
    - name: Test public API read search
      run: py.test --junitxml orcid/.py_env/Scripts/results/test_public_api_read_search.xml orcid/test_public_api_read_search.py
